POST http://localhost:3000/register HTTP/1.1
content-type: application/json


{
    "first_name":"Ellesia",
    "surname":"Janto",
    "email":"elle@bookster.com",
    "password":"pizza",
    "bio":"I am an aspiring front end web developer who loves latte art",
    "fav_book":"Harry Potter"
}

### 
GET http://localhost:3000/mybooks