POST http://localhost:3000/register HTTP/1.1
content-type: application/json


{
    "first_name":"Gorilla 3",
    "surname":"Drews",
    "email":"captaindrews@gmail.com",
    "password":"imogen",
    "bio":"I am an aspiring front end web developer who loves latte art",
    "fav_book":"To Kill a Mockingbird"
}

### 

POST http://localhost:3000/login HTTP/1.1
content-type: application/json


{
    
    "email":"captaindrews@gmail.com",
    "password":"imogen"
   
}

###

GET http://localhost:3000/register



###
GET http://localhost:3000/chat

GET http://localhost:3000/mybooks

